theme: monophase #jekyll-theme-minimal
title: ADA METAL Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
