theme: jekyll-theme-minimal
title: ADA METAL Website 
description: ADA METAL Team project website
show_downloads: False
navigation:
  - title: Report
    url: /

author.name: ADA METAL
author.url: "https://github.com/orgs/epfl-ada/teams/metal2024"